[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/MAX3015_library@^2.0.1
    adafruit/Adafruit Unified Sensor@^1.1.9
    bblanchon/ArduinoJson@^7.0.0
    links2004/WebSockets@^2.6.0
build_flags =
    -D WIFI_SSID=\"${env.WIFI_SSID}\"
    -D WIFI_PASS=\"${env.WIFI_PASS}\"
    -D API_HOST=\"${env.API_HOST}\"
